### ISSUE TITLE
docker starts but with errors and message forwarding doesn't work

### ISSUE THREAD

**Issue by pejotigrek** [AlexR1712/messenger-to-telegram#18]
as in title, my docker build-and-run log looks like this:

```
Building web
Step 1/9 : FROM node:alpine
alpine: Pulling from library/node
0a6724ff3fcd: Pull complete
f59e82757acf: Pull complete
2b54ac9d1042: Pull complete
cb081fe40633: Pull complete
Digest: sha256:5b91260f78485bfd4a1614f1afa9afd59920e4c35047ed1c2b8cde4f239dd79b
Status: Downloaded newer image for node:alpine
 ---> 5304e0d27d98
Step 2/9 : RUN mkdir -p /usr/src/app
 ---> Running in 5bcde2221c8e
Removing intermediate container 5bcde2221c8e
 ---> c5b273a7a5be
Step 3/9 : RUN mkdir -p /usr/src/app/node_modules
 ---> Running in 7951bd10f1a0
Removing intermediate container 7951bd10f1a0
 ---> 0dee419482f5
Step 4/9 : COPY ./app /usr/src/app
 ---> ed69bf2c8ba6
Step 5/9 : WORKDIR /usr/src/app
 ---> Running in 9436cb584c26
Removing intermediate container 9436cb584c26
 ---> c709c5d13db6
Step 6/9 : RUN ls -la /usr/src/app
 ---> Running in a2dacf475bcf
total 32
drwxr-xr-x    1 root     root          4096 Dec 26 00:50 .
drwxr-xr-x    1 root     root          4096 Dec 26 00:50 ..
-rw-r--r--    1 root     root          5205 Dec 26 00:36 bot.js
drwxr-xr-x    2 root     root          4096 Dec 26 00:36 images
drwxr-xr-x    1 root     root          4096 Dec 26 00:41 node_modules
-rw-r--r--    1 root     root           451 Dec 26 00:36 package.json
-rw-r--r--    1 root     root           358 Dec 26 00:36 utils.js
Removing intermediate container a2dacf475bcf
 ---> d17959249b41
Step 7/9 : RUN npm install
 ---> Running in 97589b90c9e3
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 218 packages, and audited 219 packages in 26s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Removing intermediate container 97589b90c9e3
 ---> 5f33fc89263e
Step 8/9 : RUN ls -la /usr/src/app
 ---> Running in c953447a5b15
total 176
drwxr-xr-x    1 root     root          4096 Dec 26 00:51 .
drwxr-xr-x    1 root     root          4096 Dec 26 00:50 ..
-rw-r--r--    1 root     root          5205 Dec 26 00:36 bot.js
drwxr-xr-x    2 root     root          4096 Dec 26 00:36 images
drwxr-xr-x    1 root     root          4096 Dec 26 00:51 node_modules
-rw-r--r--    1 root     root        143842 Dec 26 00:51 package-lock.json
-rw-r--r--    1 root     root           451 Dec 26 00:51 package.json
-rw-r--r--    1 root     root           358 Dec 26 00:36 utils.js
Removing intermediate container c953447a5b15
 ---> 79d9ed893b38
Step 9/9 : CMD [ "npm", "start" ]
 ---> Running in e62dd52fc259
Removing intermediate container e62dd52fc259
 ---> 3005b50122ff

Successfully built 3005b50122ff
Successfully tagged messenger-to-telegram_web:latest
WARNING: Image for service web was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating messenger-to-telegram_web_1 ... done
Attaching to messenger-to-telegram_web_1
web_1  |
web_1  | > messenger-to-telegram@1.0.0 start
web_1  | > node bot.js
web_1  |
web_1  | info login Logging in...
web_1  | info login Logged in
web_1  | info login Request to reconnect
web_1  | info login Done logging in.
web_1  | Save session to appstate.json
web_1  | ERR! listen Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
web_1  | ERR! listen     at /usr/src/app/node_modules/facebook-chat-api/utils.js:1042:15
web_1  | ERR! listen     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
web_1  | ERR! listen     at Function.Promise.attempt.Promise.try (/usr/src/app/node_modules/bluebird/js/release/method.js:39:29)
web_1  | ERR! listen     at /usr/src/app/node_modules/facebook-chat-api/utils.js:989:24
web_1  | ERR! listen     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
web_1  | ERR! listen     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
web_1  | ERR! listen     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
web_1  | ERR! listen     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
web_1  | ERR! listen     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:729:18)
web_1  | ERR! listen     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:673:18)
web_1  | ERR! listen     at Promise._resolveCallback (/usr/src/app/node_modules/bluebird/js/release/promise.js:466:57)
web_1  | ERR! listen     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:559:17)
web_1  | ERR! listen     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
web_1  | ERR! listen     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
web_1  | ERR! listen     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:729:18)
web_1  | ERR! listen     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:673:18)
web_1  | ERR! listen     at Request._callback (/usr/src/app/node_modules/bluebird/js/release/nodeback.js:45:21)
web_1  | ERR! listen     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
web_1  | ERR! listen     at Request.emit (node:events:376:20)
web_1  | ERR! listen     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
web_1  | ERR! listen     at Request.emit (node:events:376:20)
web_1  | ERR! listen     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
web_1  | ERR! listen  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
web_1  | ERR! listen     at /usr/src/app/node_modules/facebook-chat-api/utils.js:1042:15
web_1  | ERR! listen     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
web_1  | ERR! listen     at Function.Promise.attempt.Promise.try (/usr/src/app/node_modules/bluebird/js/release/method.js:39:29)
web_1  | ERR! listen     at /usr/src/app/node_modules/facebook-chat-api/utils.js:989:24
web_1  | ERR! listen     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
web_1  | ERR! listen     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
web_1  | ERR! listen     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
web_1  | ERR! listen     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
web_1  | ERR! listen     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:729:18)
web_1  | ERR! listen     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:673:18)
web_1  | ERR! listen     at Promise._resolveCallback (/usr/src/app/node_modules/bluebird/js/release/promise.js:466:57)
web_1  | ERR! listen     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:559:17)
web_1  | ERR! listen     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
web_1  | ERR! listen     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
web_1  | ERR! listen     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:729:18)
web_1  | ERR! listen     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:673:18)
web_1  | ERR! listen     at Request._callback (/usr/src/app/node_modules/bluebird/js/release/nodeback.js:45:21)
web_1  | ERR! listen     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
web_1  | ERR! listen     at Request.emit (node:events:376:20)
web_1  | ERR! listen     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
web_1  | ERR! listen     at Request.emit (node:events:376:20)
web_1  | ERR! listen     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
web_1  | Unhandled rejection TypeError: Cannot read property 'threadID' of undefined
web_1  |     at callback (/usr/src/app/bot.js:35:35)
web_1  |     at /usr/src/app/node_modules/facebook-chat-api/src/listen.js:536:11
web_1  |     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
web_1  |     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
web_1  |     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
web_1  |     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
web_1  |     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:725:18)
web_1  |     at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:93:12)
web_1  |     at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:86:9)
web_1  |     at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:102:5)
web_1  |     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:15:14)
web_1  |     at processImmediate (node:internal/timers:463:21)
```

and then - cointainer is running, but no message is forwarded.
what can I do?

**Comment by Egregius** [comment]
Exactly the same error here.

**Comment by andrewlytvyn** [comment]
I have the same, and if you can see problem with facebook-chat-api
> Exactly the same error here.

**Comment by pejotigrek** [comment]
> I have the same, and if you can see problem with facebook-chat-api

so if I understand correctly - there's nothing we can do as it is some issue on the facebook's api part?

**Comment by Egregius** [comment]
I think Facebook has changed something, like they often do.
The repo https://github.com/Schmavery/facebook-chat-api has to be updated accordingly.

**Comment by andrewlytvyn** [comment]
> I think Facebook has changed something, like they often do.
> 
> The repo https://github.com/Schmavery/facebook-chat-api has to be updated accordingly.

Exactly

**Comment by AlexR1712** [comment]
Guys I will be reviewing the project again I had been a little busy these months I will make it work as it did before and with many more improvements and integrations thank you very much for the comments that will let me know where to start from :D

This project was born as a simple experiment, I didn't think it would be used by more people. 😄

**Comment by Egregius** [comment]
Thank you Alex!
Guess it can happen that people find your code if you post it on Github ;)
For me there is no need for other integrations. I just refuse to use the Messenger app and site. Unfortunately there are few friends that refuse to use Telegram...

**Comment by fgrosswig** [comment]
> This project was born as a simple experiment, I didn't think it would be used by more people. 😄

Thanks mate, tbh ... since FB and Whatsapp changes their privacy policy this gets a run off ... count me in for getting this done :)

**Comment by AlexR1712** [comment]
Facebook UnOfficial API is not currently working as before, we need to do some workarround :D 
https://github.com/Schmavery/facebook-chat-api/issues/862

**Comment by K0-RR** [comment]
Hello, is there any progress with this? I'm not asking for eta, I'm just in the same situation as @Egregius and would like to use this.

**Comment by pejotigrek** [comment]
> Hello, is there any progress with this? I'm not asking for eta, I'm just in the same situation as @Egregius and would like to use this.

tell me about it.. I've got literally less then 10 friends that are "regulars" on messenger and just won't install Telegram "because of reasons".. so still keeping my fingers crossed for this project
